### ISSUE TITLE
Last release lacks APK file

### ISSUE THREAD

**Issue by IzzySoft** [Justin-Credible/Smart-Home-Mobile#26]
Hi, and thanks for making your app available via Github! I've just noticed the last 2 releases lack the `.apk` file. Is there any reason behind that – or would you consider adding it again to the latest release? For [some background](https://android.izzysoft.de/repo/apk/net.justincredible.smarthomemobile), that would allow me automatically getting the always latest version :stuck_out_tongue_winking_eye:

**Comment by Justin-Credible** [comment]
Hello!

Version 1.1.2 is the latest release for iOS/Android. Version 1.2.0 was built specifically for Windows 10 on Raspberry Pi. The new features are specific to that platform, so if you are running 1.1.2 on Android you aren't missing anything.

I will continue to make APKs for new versions as they are released.

**Comment by IzzySoft** [comment]
Thanks for your response, Justin – and for making the APK available this way! I'll continue keeping it updated on my end then as well (ignoring the "warnings" of my updater script concerning "missing versions"), so if anyone w/o Playstore wants to be "updated automatically", be free to refer to my repo :)

Thanks again!
